// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { testDb } from "@utils/database.ts";

import UserTastePreferencesConcept from "./UserTastePreferences/UserTastePreferencesConcept.ts";
import FeedbackConcept from "./Feedback/FeedbackConcept.ts";
import RestaurantMenuConcept from "./RestaurantMenu/RestaurantMenuConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import UserAuthenticationConcept from "./UserAuthentication/UserAuthenticationConcept.ts";

export type { default as UserTastePreferencesConcept } from "./UserTastePreferences/UserTastePreferencesConcept.ts";
export type { default as FeedbackConcept } from "./Feedback/FeedbackConcept.ts";
export type { default as RestaurantMenuConcept } from "./RestaurantMenu/RestaurantMenuConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as UserAuthenticationConcept } from "./UserAuthentication/UserAuthenticationConcept.ts";

// Initialize the database connection
export const [db, client] = await testDb();

export const UserTastePreferences = Engine.instrumentConcept(new UserTastePreferencesConcept(db));
export const Feedback = Engine.instrumentConcept(new FeedbackConcept(db));
export const RestaurantMenu = Engine.instrumentConcept(new RestaurantMenuConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const UserAuthentication = Engine.instrumentConcept(new UserAuthenticationConcept(db));
