// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually.


import type { Sync } from "@engine";

import * as sync_feedback from "./feedback.sync.ts";
import * as sync_usertastepreferences from "./usertastepreferences.sync.ts";
import * as sync_userauth from "./userauth.sync.ts";

const allSyncs: Record<string, Sync> = {};


for (const [name, func] of Object.entries(sync_feedback)) {
  if (typeof func === "function") {
    allSyncs[`feedback.${name}`] = func as Sync;
  }
}
for (const [name, func] of Object.entries(sync_usertastepreferences)) {
  if (typeof func === "function") {
    allSyncs[`usertastepreferences.${name}`] = func as Sync;
  }
}
for (const [name, func] of Object.entries(sync_userauth)) {
  if (typeof func === "function") {
    allSyncs[`userauth.${name}`] = func as Sync;
  }
}

export default allSyncs;
