// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually.


import type { Sync } from "@engine";

import * as sync_auth from "./auth.sync.ts";
import * as sync_feedback from "./feedback.sync.ts";
import * as sync_userTastePreferences from "./userTastePreferences.sync.ts";
import * as sync_restaurantMenu from "./restaurantMenu.sync.ts";
import * as sync_recommend from "./recommend.sync.ts";

const allSyncs: Record<string, Sync> = {};


for (const [name, func] of Object.entries(sync_auth)) {
  if (typeof func === "function") {
    allSyncs[`auth.${name}`] = func as Sync;
  }
}
for (const [name, func] of Object.entries(sync_feedback)) {
  if (typeof func === "function") {
    allSyncs[`feedback.${name}`] = func as Sync;
  }
}
for (const [name, func] of Object.entries(sync_userTastePreferences)) {
  if (typeof func === "function") {
    allSyncs[`userTastePreferences.${name}`] = func as Sync;
  }
}
for (const [name, func] of Object.entries(sync_restaurantMenu)) {
  if (typeof func === "function") {
    allSyncs[`restaurantMenu.${name}`] = func as Sync;
  }
}
for (const [name, func] of Object.entries(sync_recommend)) {
  if (typeof func === "function") {
    allSyncs[`recommend.${name}`] = func as Sync;
  }
}

export default allSyncs;
